# Generated by Django 4.2.1 on 2023-06-17 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="classroom",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("teacherID", models.CharField(default="0000000000", max_length=10)),
                ("name", models.CharField(default="Classroom", max_length=30)),
                ("num_students", models.IntegerField(default=0)),
                ("students", models.TextField(blank=True)),
                ("teacher", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("num_classrooms", models.IntegerField(default=0)),
                ("num_students", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("teacherID", models.CharField(default="0000000000", max_length=10)),
                ("extracurriculars", models.TextField(blank=True)),
                (
                    "introverted_extroverted",
                    models.CharField(blank=True, max_length=20),
                ),
                ("interests", models.TextField(blank=True)),
                ("who_you_are", models.TextField(blank=True)),
                ("county_in_california", models.CharField(blank=True, max_length=30)),
                ("future_career_aspirations", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
