# Generated by Django 4.2.1 on 2023-06-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_studentprofile_casual_environment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="chosenCareerField",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
